version: 1
formatters:
  simple:
    format: '%(asctime)s.%(msecs)03d - (%(filename)s).%(funcName)s(%(lineno)d) - [%(levelname)s]: %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /home/app/tactile_sensor_velostat/log/logging.log
    when: s
    backupCount: 10
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propogate: no
root:
  level: DEBUG
  handlers: []
  propogate: no