version: 1
formatters:
  simple:
    format: '%(asctime)s - (%(filename)s).%(funcName)s(%(lineno)d) - [%(levelname)s]: %(message)s'
    # datefmt: '%d.%m.%Y %H:%M:%S,%03d'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ../log/logging.log
    maxBytes: 200000
    backupCount: 5
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console,file]
    propogate: no
root:
  level: DEBUG
  handlers: []
  propogate: no