function experiment1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXPERIMENT1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a cell array.
%
%  EXPERIMENT1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  experiment1 = importfile("/home/lupasic/Programs/python_ws/tactile-sensor-velostat/src/velostat_data/experiment_1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jun-2021 13:11:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
experiment1 = readtable(filename, opts);

%% Convert to output type
experiment1 = table2cell(experiment1);
numIdx = cellfun(@(x) ~isnan(str2double(x)), experiment1);
experiment1(numIdx) = cellfun(@(x) {str2double(x)}, experiment1(numIdx));
end